### ISSUE TITLE
Translator changed the authentication

### ISSUE THREAD

**Issue by chriswendt1** [openlabs/Microsoft-Translator-Python-API#31]
@sharoonthomas , thanks for publishing useful samples for Microsoft Translator. Would you mind updating your samples to use the current authentication method? The previous version has been retired.

Thank you so much,
Chris Wendt
Microsoft Translator

**Comment by sharoonthomas** [comment]
@chriswendt1 can you take a look at this PR please? https://github.com/fulfilio/Microsoft-Translator-Python-API/pull/2
